### ISSUE TITLE
Ability to disable sensors

### ISSUE THREAD

**Issue by nickgreenway** [rylee-s/Homebridge-Litter-Robot-4#4]
I downloaded this plugin to be able to start the Air Purifier when the cat uses the litter robot. I am not a fan of the waste drawer level since it throws off the home humidity average. I would be very grateful for an option to disable this in the config.

**Comment by rylee-s** [comment]
Sounds like a necessary addition! I am aiming to get a new version pushed out this week that remedies this. Thanks for the feedback!

**Comment by nickgreenway** [comment]
That's awesome. Thank you so much!

**Comment by thesimpsonkid** [comment]
i also would like it to display as something other than humidity. and would it be possible to add a manual cycle button? this is the only working plugin for litter robot I have been able to find. Thank you.

**Comment by telunc** [comment]
> i also would like it to display as something other than humidity. and would it be possible to add a manual cycle button? this is the only working plugin for litter robot I have been able to find. Thank you.

I also found this library https://github.com/natekspencer/pylitterbot
It might be helpful for someone who like to learn about the litter robot API. It has manual cycle, reset robot, and more.

**Comment by rylee-s** [comment]
Howdy! I just pushed v3.1.0 with this feature if you guys wanna check it out. Sorry for the super late response

**Comment by nickgreenway** [comment]
Thank you so much! It works great!

**Comment by thesimpsonkid** [comment]
I don't understand. I updated, failed, then uninstalled and reinstalled 3.1 plugin and I am still seeing it as a humidity sensor and there is still no cycle button. What changed? I don't mean to be rude and I'm hoping I am doing something wrong. Thank you.

**Comment by thesimpsonkid** [comment]
I see now this was just to disable drawer sensors. I'm sorry my comments/interest was off topic. I need to read more thoroughly. Sorry, Have a good day.
